# Etapa base: Python 3.11 con menor tamaño
FROM python:3.11-slim

# Establece directorio de trabajo
WORKDIR /app

# Copia solo los archivos necesarios
COPY app/ /app/
COPY app/requirements.txt /app/requirements.txt
COPY .env /app/.env

# Instala solo lo necesario y limpia cache
RUN pip install --no-cache-dir --upgrade pip \
 && pip install --no-cache-dir -r requirements.txt

# Comando de inicio
CMD ["python", "run.py"]
